force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <description>Specifies the Name of the Customer.</description>
    <inlineHelpText>Specifies the Name of the Customer.</inlineHelpText>
    <label>Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Specifies the Email of the customer.</description>
    <inlineHelpText>Specifies the Email of the customer.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <description>Specifies the Phone Number of the Customer.</description>
    <inlineHelpText>Specifies the Phone Number of the Customer.</inlineHelpText>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Related_to_Contact__c.field-meta.xml
<CustomField>
    <fullName>Related_to_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Specifies the Contact to which the Customer is related with.</description>
    <inlineHelpText>Specifies the Contact to which the Customer is related with.</inlineHelpText>
    <label>Related to Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Shipping_Charge__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Charge__c</fullName>
    <label>Shipping Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/InvoicePaymentControllerTest.cls
@isTest
public class InvoicePaymentControllerTest {
    private static testmethod void MyTest(){
         Account objAccount = new Account();
        objAccount.Name = 'Test Account';
        insert objAccount;
        
        Contact objContact = new Contact();
        objContact.FirstName = 'Test';
        objContact.LastName = 'Contact';
        objContact.AccountId = objAccount.Id;
        objContact.MailingState = 'Sample City';
        insert objContact; 
        
        Invoice__c objInvoice = new Invoice__c();
        objInvoice.Name = 'Test';
        objInvoice.Related_to_Contact__c = objContact.Id;
        objInvoice.BOATBUILDING__Contact_Name__c = objContact.Id;
        objInvoice.Customer_Name__c = objInvoice.Related_to_Contact__r.Name;
        objInvoice.Phone_Number__c = objInvoice.Related_to_Contact__r.Phone;
        objInvoice.Email__c = 'test@123.com';
        objInvoice.Shipping_Charge__c = 10000;
        insert objInvoice;
        InvoicePaymentController.getPaymentURLInfo(objInvoice.Id);
        InvoicePaymentController.getType(objInvoice.Id);
        
        
        
    }

}