force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <description>This object will hold the necessary details about the product available in stock.</description>
    <label>Inventory</label>
    <nameField>
        <displayFormat>Inventory-{0000}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Part_MSRP_Price__c.field-meta.xml
<CustomField>
    <fullName>Part_MSRP_Price__c</fullName>
    <label>Part MSRP Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <label>Part Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantity</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Taxable__c.field-meta.xml
<CustomField>
    <fullName>Taxable__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Specifies whether the price of the item would be inclusive of taxes on Payment, or not.</inlineHelpText>
    <label>Taxable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Manufacturer__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Manufacturer__c</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parts_Availability__c/Parts_Availability__c.object-meta.xml
<CustomObject>
    <label>Parts Availability</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Parts Availability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts Availability</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Parts_Availability__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Parts Availability</relationshipLabel>
    <relationshipName>Parts_Availability</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Parts_Availability__c/fields/Store_Location__c.field-meta.xml
<CustomField>
    <fullName>Store_Location__c</fullName>
    <label>Store Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Store_Location</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store_Location__c/Store_Location__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Store Location</label>
</CustomObject>

force-app/main/default/classes/ReceiveAllAtLocation.cls
public with sharing class ReceiveAllAtLocation {
    @AuraEnabled
    public static String partAvailabilityAtLocation(String selectedLocation, List<OrderEditWrapper> lstlistItem) {
        System.debug('>>>> before try lstlistItem : '+lstlistItem);
        try { 
            System.debug('>>>>lstlistItem : '+lstlistItem);
            Set<String> setPartNumbers =  new Set<String>();
            List<Parts_Availability__c> lstPA = new List<Parts_Availability__c>();
            Map<String, BOATBUILDING__Inventory__c> mapInv = new Map<String, BOATBUILDING__Inventory__c>();
            for(OrderEditWrapper obj:lstlistItem){
                setPartNumbers.add(obj.partNo);
            }
            Id InvenRecId = Schema.SObjectType.BOATBUILDING__Inventory__c.getRecordTypeInfosByName().get('Inventory for Parts').getRecordTypeId();        
            
            List<BOATBUILDING__Inventory__c> lstUpdatedInventory = new List<BOATBUILDING__Inventory__c>();
            List<BOATBUILDING__Inventory__c> lstInventory =[SELECT Id, Vendor__c, Cost__c, Part_Number__c, Part_MSRP_Price__c, Description__c, Quantity__c,
                                                            Taxable__c, Weight__c,
                                                            (Select Id, IsDeleted, Name, BOATBUILDING__Inventory__c, 
                                                             BOATBUILDING__Quantity__c, BOATBUILDING__Store_Location__c 
                                                             From BOATBUILDING__Parts_Availability__r)FROM BOATBUILDING__Inventory__c 
                                                            WHERE RecordTypeId =:invenRecId AND BOATBUILDING__Part_Number__c IN:setPartNumbers];
            for(BOATBUILDING__Inventory__c objInv :lstInventory){
                mapInv.put(objInv.BOATBUILDING__Part_Number__c,objInv);
            }
            for(OrderEditWrapper obj:lstlistItem){
                
                BOATBUILDING__Inventory__c objInventory = new BOATBUILDING__Inventory__c();
                if(mapInv.containskey(obj.partNo)){
                    objInventory = mapInv.get(obj.partNo) ;   
                } 
                if(objInventory.BOATBUILDING__Quantity__c != null){
                    objInventory.BOATBUILDING__Quantity__c  += obj.quantity ;
                }else{
                    objInventory.BOATBUILDING__Quantity__c  = obj.quantity ;    
                }
                objInventory.BOATBUILDING__Part_Number__c =obj.partNo;
                objInventory.RecordTypeId = InvenRecId;
                lstUpdatedInventory.add(objInventory); 
            }
            upsert lstUpdatedInventory;
            
            for(Inventory__c obj: lstUpdatedInventory) {
                
                for(OrderEditWrapper objOrderEditWrapper:lstlistItem){
                    
                    if(obj.BOATBUILDING__Parts_Availability__r.isEmpty()) {
                        for(Parts_Availability__c objPA: objOrderEditWrapper.lstPA) {
                            Parts_Availability__c objPAIN = new Parts_Availability__c();
                            objPAIN = objPA;
                            objPAIN.Inventory__c = obj.Id;
                            lstPA.add(objPAIN);
                        }
                    } else if(!obj.BOATBUILDING__Parts_Availability__r.isEmpty()) {
                        
                        Map<String, Parts_Availability__c> mapStoreLocToPA = new Map<String, Parts_Availability__c>();
                        for(Parts_Availability__c objPA : obj.BOATBUILDING__Parts_Availability__r) {
                            mapStoreLocToPA.put(objPA.Store_Location__c, objPA);
                        }
                        
                        for(Parts_Availability__c objPA: objOrderEditWrapper.lstPA) {
                            if(mapStoreLocToPA.containsKey(objPA.BOATBUILDING__Store_Location__c)){
                                Parts_Availability__c objPAIN = mapStoreLocToPA.get(objPA.BOATBUILDING__Store_Location__c);
                                objPAIN.Store_Location__c = objPA.BOATBUILDING__Store_Location__c;
                                if(objPAIN.BOATBUILDING__Quantity__c != null) {
                                    objPAIN.BOATBUILDING__Quantity__c += objPA.BOATBUILDING__Quantity__c;
                                } else { 
                                    objPAIN.BOATBUILDING__Quantity__c = objPA.BOATBUILDING__Quantity__c;
                                } 
                                lstPA.add(objPAIN); 
                            } else {
                                Parts_Availability__c objPAIN = new Parts_Availability__c();
                                objPAIN.Store_Location__c = objPA.BOATBUILDING__Store_Location__c;
                                objPAIN.Inventory__c = obj.Id;
                                objPAIN.BOATBUILDING__Quantity__c = objOrderEditWrapper.quantity;
                                lstPA.add(objPAIN);
                            }
                        }
                    }
                }
                
                
            }
            return 'SUCCESS';
        }   
        catch(Exception ex) {
            System.debug('Error: '+ex.getMessage()+' Line Number: '+ex.getLineNumber());
            return 'Error: '+ex.getMessage()+' Line Number: '+ex.getLineNumber()+' : '+ex.getStackTraceString();
        }
    }
}