force-app/main/default/objects/Part__c/Part__c.object-meta.xml
<CustomObject>
    <label>Part</label>
    <nameField>
        <label>Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part__c/fields/Family1__c.field-meta.xml
<CustomField>
    <fullName>Family1__c</fullName>
    <label>Family</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category1__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Back Packs</fullName>
            </value>
            <value>
                <fullName>Bindings</fullName>
            </value>
            <value>
                <fullName>Board Racks</fullName>
            </value>
            <value>
                <fullName>Boards</fullName>
            </value>
            <value>
                <fullName>Board Shorts</fullName>
            </value>
            <value>
                <fullName>Boots</fullName>
            </value>
            <value>
                <fullName>Canvas</fullName>
            </value>
            <value>
                <fullName>Dash</fullName>
            </value>
            <value>
                <fullName>Electrical</fullName>
            </value>
            <value>
                <fullName>Engine</fullName>
            </value>
            <value>
                <fullName>Fat Sacs</fullName>
            </value>
            <value>
                <fullName>Gel</fullName>
            </value>
            <value>
                <fullName>Handles</fullName>
            </value>
            <value>
                <fullName>Hats</fullName>
            </value>
            <value>
                <fullName>Hoodies</fullName>
            </value>
            <value>
                <fullName>Life Jackets</fullName>
            </value>
            <value>
                <fullName>Lighting</fullName>
            </value>
            <value>
                <fullName>Lower Unit</fullName>
            </value>
            <value>
                <fullName>Ropes</fullName>
            </value>
            <value>
                <fullName>Rub Rail</fullName>
            </value>
            <value>
                <fullName>Running Gear</fullName>
            </value>
            <value>
                <fullName>Steering</fullName>
            </value>
            <value>
                <fullName>Stereo</fullName>
            </value>
            <value>
                <fullName>Surf Boards</fullName>
            </value>
            <value>
                <fullName>Surf Pads</fullName>
            </value>
            <value>
                <fullName>Surf Ropes</fullName>
            </value>
            <value>
                <fullName>Swimsuits</fullName>
            </value>
            <value>
                <fullName>Tee Shirts</fullName>
            </value>
            <value>
                <fullName>Tower</fullName>
            </value>
            <value>
                <fullName>Trans</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Part__c/fields/Part__c.field-meta.xml
<CustomField>
    <fullName>Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Part Variations</relationshipLabel>
    <relationshipName>Part_Variation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Part__c/fields/Sub_Family__c.field-meta.xml
<CustomField>
    <fullName>Sub_Family__c</fullName>
    <label>Sub-Family</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family1__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>Wakesurf Boards</fullName>
            </value>
            <value>
                <fullName>Wakeboards</fullName>
            </value>
            <value>
                <fullName>Ropes &amp; Handles</fullName>
            </value>
            <value>
                <fullName>Pants</fullName>
            </value>
            <value>
                <fullName>Hoodies &amp; Sweatshirts</fullName>
            </value>
            <value>
                <fullName>T-Shirts</fullName>
            </value>
            <value>
                <fullName>Packages</fullName>
            </value>
            <value>
                <fullName>Exhaust Hoses</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/System_Configure__c/System_Configure__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>System Configure</label>
</CustomObject>

force-app/main/default/objects/System_Configure__c/fields/Enable_Debug_Mails__c.field-meta.xml
<CustomField>
    <fullName>Enable_Debug_Mails__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Debug Mails</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/WooCommerce_Connect_Process_3.cls
//objPart.Family1__c
global with sharing class WooCommerce_Connect_Process_3 implements Queueable, Database.AllowsCallouts {
    Map<String, Map<String,Set<String>>> mapAttOption = new Map<String, Map<String,Set<String>>>();
    Map<String, Set<String>> mapAttNameOptionForPro = new Map<String, Set<String>>();
    String strPartId = '';
    List<BOATBUILDING__Woocommerce_Attribute__c> lstWA = new List<BOATBUILDING__Woocommerce_Attribute__c>();
    BOATBUILDING__WooCmmerce_Config__c objWC;
    Part__c objPart;
    Map<String, String> mapCollectionNameId = new Map<String, String>();
    Map<String, String> mapAttNameId = new Map<String, String>();
    String prntId;
    Map<String, String> mapAttBase64 = new Map<String, String>(); 

    global WooCommerce_Connect_Process_3(Map<String, Map<String,Set<String>>> mapAttOption, Map<String, Set<String>> mapAttNameOptionForPro, String strPartId, List<BOATBUILDING__Woocommerce_Attribute__c> lstWA, 
                                            BOATBUILDING__WooCmmerce_Config__c objWC, Part__c objPart, Map<String, String> mapCollectionNameId, Map<String, String> mapAttNameId, String prntId, 
                                                Map<String, String> mapAttBase64) {

        this.mapAttOption = mapAttOption;
        this.mapAttNameOptionForPro = mapAttNameOptionForPro;
        this.strPartId = strPartId;
        this.lstWA = lstWA;  
        this.objWC = objWC;
        this.objPart = objPart;
        this.mapCollectionNameId = mapCollectionNameId;
        this.mapAttNameId = mapAttNameId;
        this.prntId = prntId;
        this.mapAttBase64 = mapAttBase64;
    }
    global void execute(QueueableContext context) {
        String customLog = '';
        try {
            if(objPart.Family1__c != null) {
                //Callout Method
                Map<String, String> mapCollectionNameIdFam = WooCommerce_Connect.getWooCommerceCategories(objWC, objPart.Family1__c, prntId);// objPart.BOATBUILDING__Category1__c.toUpperCase()
                mapCollectionNameId.putAll(mapCollectionNameIdFam);
                System.debug('Debug Log for mapCollectionNameId F: '+mapCollectionNameId);
                String Family = objPart.Family1__c.toUpperCase(); 
                if(!mapCollectionNameId.containsKey(Family)) {
                    //Callout Method
                    Map<String, String> mapNewCollection = WooCommerce_Connect.createCustomCategoryToWoocommerce(objPart.Family1__c, objWC, prntId);
                    if(!mapNewCollection.isEmpty()){
                        mapCollectionNameId.putAll(mapNewCollection);
                        prntId = mapCollectionNameId.get(Family);
                    }
                } else {
                    prntId = mapCollectionNameId.get(Family);
                }
            }    
            if(objPart.Family1__c != null &&  objPart.Sub_Family__c != null) {
                //Callout Method
                Map<String, String> mapCollectionNameIdSBFam = WooCommerce_Connect.getWooCommerceCategories(objWC, objPart.Sub_Family__c, prntId);// objPart.BOATBUILDING__Category1__c.toUpperCase()
                mapCollectionNameId.putAll(mapCollectionNameIdSBFam);
                System.debug('Debug Log for mapCollectionNameId SF: '+mapCollectionNameIdSBFam);
                String SubFamily = objPart.Sub_Family__c.toUpperCase(); 
                if(!mapCollectionNameId.containsKey(SubFamily)) {
                    //Callout Method
                    Map<String, String> mapNewCollection = WooCommerce_Connect.createCustomCategoryToWoocommerce(objPart.Sub_Family__c, objWC, prntId);
                    if(!mapNewCollection.isEmpty()){
                        mapCollectionNameId.putAll(mapNewCollection);
                    }
                }
            }
            System.debug('Debug Log for After Add mapCollectionNameId: '+mapCollectionNameId);
            //Calling Queueable
            WooCommerce_Connect_Process_4 objWooCommerce_Connect_Process_4 = new WooCommerce_Connect_Process_4(mapAttOption, mapAttNameOptionForPro, strPartId, lstWA, objWC, objPart, mapCollectionNameId, mapAttNameId, prntId, mapAttBase64);
            System.enqueueJob(objWooCommerce_Connect_Process_4);
        }
        catch(Exception ex) {
            System.debug(ex);
            System_Configure__c objSC = System_Configure__c.getOrgDefaults();
            if(objSC != null && objSC.Enable_Debug_Mails__c)  {
                BOATBUILDING__Custom_Log__c objCL = new BOATBUILDING__Custom_Log__c();
                objCL.Name = 'Woocommerce Log process 3';
                customLog += WooCommerce_Connect.catagoryResponse; 
                if(customLog.length() >= 131000) {
                    objCL.BOATBUILDING__Summary__c = customLog.substring(0,131000); 
                } else {
                    objCL.BOATBUILDING__Summary__c = customLog;  
                }
                insert objCL;
            }
        }
    }
}